// flow-typed signature: c8bfa3d6362572ec9a528a44c30f4cd8
// flow-typed version: <<STUB>>/get-caller-file_v^1.0.2/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-caller-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "get-caller-file" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "get-caller-file/index" {
  declare module.exports: $Exports<"get-caller-file">;
}
declare module "get-caller-file/index.js" {
  declare module.exports: $Exports<"get-caller-file">;
}
